### PR TITLE
chore: Move simapp to its own package

### PR DESCRIPTION
**Pull request by Eric-Warehime**
Moves simapp out of the core `slinky` package. Run `make tidy` afterwards.

Resulted in 5 top level deps removed from the top level package and many indirect deps.

### CODE REVIEW

**Comment by Eric-Warehime** [comment]
> @check-spelling-bot apply [updates](https://github.com/skip-mev/slinky/actions/runs/10412249779/attempts/1).

**Review by technicallyty — APPROVED** [review]
major W

**Review by aljo242 — APPROVED** [review]
Huge

**Comment by aljo242** [comment]
@Eric-Warehime looks like e2e is railing to resolve imports

**Pull request merged**
