### PR TITLE
feat: Local SideCar Dashboard

### PR DESCRIPTION
**Pull request by davidterpay**

### CODE REVIEW

**Review by aljo242 — APPROVED** [review]

**Review by Eric-Warehime — COMMENTED** [review]
Why do you want to move this file to this directory?

**Comment by davidterpay** [comment]
> Why do you want to move this file to this directory?

that is the default file dir structure for grafana dashboards. i accidentally misplaced in previous PR and got merged before i could make the fix. rn it expects to scrape from that directory which is why if you run it it wont work.

**Comment by Eric-Warehime** [comment]
> > Why do you want to move this file to this directory?
> 
> that is the default file dir structure for grafana dashboards. i accidentally misplaced in previous PR and got merged before i could make the fix. rn it expects to scrape from that directory which is why if you run it it wont work.

👍

**Review by Eric-Warehime — APPROVED** [review]

**Comment by davidterpay** [comment]
i'm going to make a few additional changes so pls do not merge

**Pull request merged**
