### PR TITLE
chore: minor cleanup

### PR DESCRIPTION
**Pull request by tac0turtle**
this pr removes some `sdk.Context` usage as its not needed. It also preps migration for 52/v2

happy to reduce scope. just saw some cleanup while reading the code

### CODE REVIEW

**Review by aljo242 — APPROVED** [review]

**Comment by aljo242** [comment]
test failing is just a flaky test we will be fixing

**Review by Eric-Warehime — APPROVED** [review]

**Comment by tac0turtle** [comment]
What's the process to get this merged? Anything I have to do?

**Comment by aljo242** [comment]
> What's the process to get this merged? Anything I have to do?

No, I was just waiting on us to make a release earlier next week before merging.  I'll merge this

**Comment by tac0turtle** [comment]
> > What's the process to get this merged? Anything I have to do?
> 
> No, I was just waiting on us to make a release earlier next week before merging. I'll merge this

ah okay, my bad. didnt see an update so was unsure

**Pull request merged**
