### PR TITLE
fix: dont generate pulsar code for "service" 

### PR DESCRIPTION
**Pull request by technicallyty**
- ignores the `service` directory for generating pulsar code.
- runs `make proto-all`
- updates proto comment for decimals to match whats in the docs

### CODE REVIEW

**Comment by technicallyty** [comment]
99.99999% of the diff is file descriptor changes from proto gen

**Comment by technicallyty** [comment]
no way there is a spelling error in one of the code generators 😀

**Review by aljo242 — APPROVED** [review]
just needs spellcheck push RIP

**Comment by technicallyty** [comment]
@check-spelling-bot apply [updates](https://github.com/skip-mev/connect/actions/runs/10534109743/attempts/1).

**Pull request merged**
